# Generated by Django 4.1.1 on 2022-09-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_appointment_appointment_with_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time_start')},
        ),
    ]
