# Generated by Django 4.1.1 on 2022-09-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
    ]
