# Generated by Django 4.1.1 on 2022-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_appointment_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_end',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_start',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
